name: Bug report / Bug 报告
description: Report a bug you found when using TUNA mirrors / 报告在使用 TUNA 镜像站时出现的 bug
labels: ["Service Issue"]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        请使用此模板来报告 bug，并尽可能多地提供信息。
        Please use this template while reporting a bug and provide as much info as possible.
  - type: textarea
    id: what_happened
    attributes:
      label: 发生了什么（What happened）
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: 期望的现象（What you expected to happen）
    validations:
      required: true
  - type: textarea
    id: how_to_reproduce
    attributes:
      label: 如何重现此问题（How to reproduce it）
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: 操作系统（OS Version）
  - type: input
    id: browser
    attributes:
      label: 浏览器（如果适用）（Browser version, if applicable）
  - type: textarea
    id: other_env
    attributes:
      label: 其他环境（Other environments）
  - type: textarea
    id: others
    attributes:
      label: 其他需要说明的事项（Anything else we need to know）
  - type: checkboxes
    id: terms
    attributes:
      label: 注意事项 (Confirmations)
      options:
        - label: |
            我已确认这个问题没有在其他 issue 中提出过。
            I am sure that this problem has NEVER been discussed in other issues.
