name: Unblock request / 解封请求
description: Request to unblock your IP address on TUNA Mirrors / 请求解封从 TUNA 镜像站解封您的 IP 地址
labels: ["Unblock Request"]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        如果您在镜像站上看到了封禁页面，可以使用此模板提交信息请求解封，但**不要包含任何敏感信息**。
        如果您无法访问镜像站，请向 support AT tuna DOT tsinghua DOT edu DOT cn 发送邮件。  
        Please use this template to request unblocking of your IP address if you are seeing forbidden pages on TUNA Mirrors.
        **DO NOT include any sensitive information**.
        If you cannot access the mirror site at all, please send an email to support AT tuna DOT tsinghua DOT edu DOT cn.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: 先决条件 (Prerequisites)
      options:
        - label: |
            我已确认我没有就相同的网络环境提出请求。
            I have confirmed that I have not made a request within the same network environment.
          required: true
        - label: |
            我已确认我没有在请求中包含敏感信息（如 IP 地址，具体地理位置等）。
            I have confirmed that I have not included any sensitive information (e.g., specific IP address or exact geographic location) in the request.
          required: true
        - label: |
            我承诺此前没有，将来也不会滥用 TUNA 镜像站。
            I promise that I have not abused TUNA Mirrors in the past and will not do so in the future.
          required: true
        - label: |
            我理解 TUNA 并不一定会解封我的 IP 地址，或者对封禁做出任何解释。
            I understand that TUNA is not obligated to unblock my IP address or provide any explanation for the block.
          required: true
  - type: textarea
    id: forbidden_url
    attributes:
      label: 被封禁的 URL（The URL you tried to access）
    validations:
      required: true
  - type: textarea
    id: forbidden_code
    attributes:
      label: 页面上红色的形如 `00000088` 的十六进制状态代码（Red hexadecimal status code like `00000088` on the page）
    validations:
      required: true
  - type: textarea
    id: access_id
    attributes:
      label: 页面上红色的十六字节请求编码（Red hexadecimal request ID on the page）
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: 操作系统（OS Version）
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 访问用软件和版本（Software used for access and version）
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: 您下载的目的（Purpose of your access）
